export type ActionType =
  | 'PDF_IMG_CONVERSION'
  | 'IMG_TO_JSON_SCHEMA'
  | 'ENTITY_JSON_SCHEMA_MATCH'
  | 'CREATE_QUICKBOOKS_BILL'
  | 'POST_JSON_SCHEMA'
  | 'UPLOAD_IMAGE_TO_ENDPOINT'
  | 'ENTITY_JSON_SCHEMA_RANKING';

export const ACTION_TYPE_VALUES: ActionType[] = [
  'PDF_IMG_CONVERSION',
  'IMG_TO_JSON_SCHEMA',
  'ENTITY_JSON_SCHEMA_MATCH',
  'CREATE_QUICKBOOKS_BILL',
  'POST_JSON_SCHEMA',
  'UPLOAD_IMAGE_TO_ENDPOINT',
  'ENTITY_JSON_SCHEMA_RANKING',
];
