export type CronScheduleType =
  | 'EVERY_MINUTE'
  | 'EVERY_5_MINUTES'
  | 'EVERY_30_MINUTES'
  | 'EVERY_HOUR'
  | 'EVERY_3_HOURS'
  | 'EVERY_6_HOURS'
  | 'EVERY_12_HOURS'
  | 'EVERY_DAY';

// USED IN DTOs
export const CRON_SCHEDULE_TYPE_VALUES: CronScheduleType[] = [
  'EVERY_MINUTE',
  'EVERY_5_MINUTES',
  'EVERY_30_MINUTES',
  'EVERY_HOUR',
  'EVERY_3_HOURS',
  'EVERY_6_HOURS',
  'EVERY_12_HOURS',
  'EVERY_DAY',
];
