export type ScheduledJobType =
  | 'GMAIL_INBOUND_EMAIL'
  | 'DROPBOX_INBOUND_FILES'
  | 'GOOGLE_DRIVE_INBOUND_FILES'
  | 'S3_INBOUND_FILES'
  | 'CLOUD_STORAGE_INBOUND_FILES';

// USED IN DTOs
export const SCHEDULED_JOB_TYPE_VALUES: ScheduledJobType[] = [
  'GMAIL_INBOUND_EMAIL',
  'DROPBOX_INBOUND_FILES',
  'GOOGLE_DRIVE_INBOUND_FILES',
  'S3_INBOUND_FILES',
  'CLOUD_STORAGE_INBOUND_FILES',
];
