export type StepFailureType =
  | 'ACTION_ERROR'
  | 'CHILD_WORKFLOW'
  | 'INPUT_VALIDATION'
  | 'OUTPUT_VALIDATION'
  | 'INPUT_RESOLUTION';

// USED IN DTOs
export const STEP_FAILURE_TYPE_VALUES: StepFailureType[] = [
  'ACTION_ERROR',
  'CHILD_WORKFLOW',
  'INPUT_VALIDATION',
  'OUTPUT_VALIDATION',
  'INPUT_RESOLUTION',
];
