export enum Queue {
  WORKER_SQS_QUEUE = 'WORKER_SQS_QUEUE',
  STRUCTURED_DATA_JOB_SPAWNER_QUEUE = 'STRUCTURED_DATA_JOB_SPAWNER_QUEUE',
  STRUCTURED_DATA_JOB_QUEUE = 'STRUCTURED_DATA_JOB_QUEUE',
  ENTITY_EMBEDDINGS_QUEUE = 'ENTITY_EMBEDDINGS_QUEUE',
}
